version: '3.8'

services:

  flask:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build:
      context: ./celery_worker
    #command: celery -A celerytask worker -l INFO -Q queue2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ../flask_app:/usr/src/app/
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine