version: '3.8'

services:

  flask:
    container_name: flask
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build:
      context: ./celery_worker
    #command: celery -A celerytask worker -l INFO -Q queue2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    volumes:
#      - ../flask_app:/usr/src/app/
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine

  gpu_test:
    image: pytorch/pytorch
    command: nvidia-smi
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  gpu_celery_worker:
    image: pytorch/pytorch
    build:
      context: ./gpu_celery_worker
    #command: nvidia-smi
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    depends_on:
      - redis